stages:
  - test
  - deploy
  - build

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  image: node:10
  stage: deploy
  script:
  - npm install gitbook-cli -g # install gitbook
  - gitbook fetch 3.2.3 # fetch final stable version
  - gitbook install # add any requested plugins in book.json
  - gitbook build . public # build to public path
  artifacts:
    paths:
      - public

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME
    CONTAINER_RELEASE_TAG: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Containerfile -t $CONTAINER_RELEASE_TAG .
    - docker push $CONTAINER_RELEASE_TAG
